export const STATUS_TO_UI = {
  DRAFT: 'Draft',
  CONFIRMED: 'Confirmed',
  PARTIALLY_RECEIVED: 'Partially Received',
  FULLY_RECEIVED: 'Fully Received',
  PARTIALLY_DELIVERED: 'Partially Delivered',
  FULLY_DELIVERED: 'Fully Delivered',
  IN_PROGRESS: 'In Progress',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  PENDING: 'Pending',
  DONE: 'Done',
};

export const mapStatus = (status) => STATUS_TO_UI[status] ?? status;

export const mapProductFromApi = (p) => ({
  id: p.id,
  name: p.name,
  sku: p.sku,
  type: p.type === 'RAW_MATERIAL' ? 'Raw Material' : 'Finished Good',
  typeRaw: p.type,
  salesPrice: p.salesPrice ?? 0,
  costPrice: p.costPrice ?? 0,
  onHand: p.onHandQty ?? p.onHand ?? 0,
  reserved: p.reservedQty ?? p.reserved ?? 0,
  freeToUse:
    p.freeToUse ??
    p.freeToUseQty ??
    (p.onHandQty ?? p.onHand ?? 0) - (p.reservedQty ?? p.reserved ?? 0),
  procurementStrategy: p.procurementStrategy ?? 'MTS',
  procureOnDemand: p.procureOnDemand ?? false,
  procurementType: p.procurementType ?? null,
  defaultVendorId: p.defaultVendorId ?? null,
  defaultVendor: p.defaultVendor ?? null,
});

export const mapProductToApi = (p) => ({
  name: p.name,
  sku: p.sku,
  type: p.typeRaw ?? (p.type === 'Raw Material' ? 'RAW_MATERIAL' : 'FINISHED_GOOD'),
  salesPrice: Number(p.salesPrice) || 0,
  costPrice: Number(p.costPrice) || 0,
  onHandQty: Number(p.onHand) || 0,
  procurementStrategy: p.procurementStrategy ?? 'MTS',
  procureOnDemand: Boolean(p.procureOnDemand),
  procurementType: p.procurementType || null,
  defaultVendorId: p.defaultVendorId ? Number(p.defaultVendorId) : null,
});

export const calcOrderTotal = (items, priceField = 'unitPrice') =>
  items.reduce((sum, i) => sum + (i.quantity ?? 0) * (i[priceField] ?? 0), 0);

export const mapPurchaseOrderFromApi = (order) => {
  const items = (order.items ?? []).map((i) => ({
    id: i.id,
    productId: i.productId,
    productName: i.product?.name ?? '',
    quantity: i.quantity,
    receivedQty: i.receivedQty ?? 0,
    unitPrice: i.product?.costPrice ?? 0,
  }));
  return {
    id: order.id,
    vendorId: order.vendorId,
    vendorName: order.vendor?.name ?? '',
    status: mapStatus(order.status),
    orderDate: order.orderDate,
    autoGenerated: order.autoGenerated ?? false,
    items,
    total: calcOrderTotal(items, 'unitPrice'),
  };
};

export const mapSalesOrderFromApi = (order) => {
  const items = (order.items ?? []).map((i) => ({
    id: i.id,
    productId: i.productId,
    productName: i.product?.name ?? '',
    quantity: i.quantity,
    deliveredQty: i.deliveredQty ?? 0,
    unitPrice: i.product?.salesPrice ?? 0,
  }));
  return {
    id: order.id,
    customerId: order.customerId,
    customerName: order.customer?.name ?? '',
    status: mapStatus(order.status),
    orderDate: order.orderDate,
    items,
    total: calcOrderTotal(items, 'unitPrice'),
  };
};

export const mapSalesOrderDetailFromApi = (order) => ({
  ...order,
  createdByUser: order.createdByUser ?? order.creator ?? null,
  items: (order.items ?? []).map((i) => ({
    ...i,
    salesUnitPrice: i.salesUnitPrice ?? i.product?.salesPrice ?? 0,
  })),
  procurementActions: order.procurementActions ?? [],
});

export const mapManufacturingOrderFromApi = (mo) => ({
  id: mo.id,
  productId: mo.productId,
  productName: mo.product?.name ?? '',
  quantity: mo.quantity,
  status: mapStatus(mo.status),
  statusRaw: mo.status,
  bomId: mo.bomId,
  autoGenerated: mo.autoGenerated ?? false,
  createdAt: mo.createdAt,
  workOrders: (mo.workOrders ?? []).map((wo) => ({
    id: wo.id,
    operationName: wo.operationName,
    workCenter: wo.workCenter,
    durationMinutes: wo.durationMinutes,
    status: mapStatus(wo.status),
    statusRaw: wo.status,
  })),
  bom: mo.bom ?? null,
});

export const mapManufacturingOrderDetailFromApi = (mo) => ({
  ...mapManufacturingOrderFromApi(mo),
  product: mo.product ? mapProductFromApi(mo.product) : null,
  assignedUser: mo.assigned ?? mo.assignedUser ?? null,
  bom: mo.bom ? mapBomFromApi(mo.bom) : null,
});

export const mapStockLedgerFromApi = (entry, products = []) => {
  const product = products.find((p) => p.id === entry.productId);
  return {
    id: entry.id,
    productId: entry.productId,
    productName: product?.name ?? '',
    changeQty: entry.changeQty,
    reason: entry.reason,
    referenceId: entry.referenceId,
    referenceType: entry.referenceType,
    timestamp: entry.timestamp,
  };
};

export const mapBomFromApi = (bom) => ({
  id: bom.id,
  finishedProductId: bom.finishedProductId,
  finishedProduct: bom.finishedProduct ?? null,
  finishedProductName: bom.finishedProduct?.name ?? '',
  components: (bom.components ?? []).map((c) => ({
    id: c.id,
    componentProductId: c.componentProductId,
    componentProduct: c.componentProduct ?? null,
    componentName: c.componentProduct?.name ?? '',
    quantityRequired: c.quantityRequired,
  })),
  operations: (bom.operations ?? []).map((o) => ({
    id: o.id,
    operationName: o.operationName,
    durationMinutes: o.durationMinutes,
    workCenter: o.workCenter,
  })),
});

export const toReceivePayload = (orderItems) =>
  orderItems
    .filter((i) => (i.receivedQty ?? 0) < i.quantity)
    .map((i) => ({
      itemId: i.id,
      quantity: i.quantity - (i.receivedQty ?? 0),
    }));

export const toDeliverPayload = (orderItems) =>
  orderItems
    .filter((i) => (i.deliveredQty ?? 0) < i.quantity)
    .map((i) => ({
      itemId: i.id,
      quantity: i.quantity - (i.deliveredQty ?? 0),
    }));

export const mapAuditLogFromApi = (log) => ({
  id: log.id,
  userId: log.userId,
  userName: log.user?.name ?? '',
  action: log.action,
  entityType: log.entityType,
  entityId: log.entityId,
  oldValue: log.oldValue,
  newValue: log.newValue,
  timestamp: log.timestamp,
});
