const prisma = require('../config/db');
const stockService = require('./stockService');

const createManufacturingOrder = async (productId, qty, userId, autoGenerated = false) => {
  const product = await prisma.product.findUnique({ where: { id: productId } });
  if (!product) {
    throw Object.assign(new Error('Product not found'), { statusCode: 404 });
  }

  const bom = await prisma.boM.findUnique({
    where: { finishedProductId: productId },
    include: { components: true, operations: true },
  });

  if (!bom) {
    throw Object.assign(new Error('BoM not found for this product'), { statusCode: 404 });
  }

  const mo = await prisma.manufacturingOrder.create({
    data: {
      productId,
      quantity: qty,
      bomId: bom.id,
      status: 'DRAFT',
      autoGenerated,
      assignedTo: userId || null,
      workOrders: {
        create: bom.operations.map((op) => ({
          operationName: op.operationName,
          workCenter: op.workCenter,
          durationMinutes: op.durationMinutes,
          status: 'PENDING',
        })),
      },
    },
    include: {
      product: true,
      bom: { include: { components: { include: { componentProduct: true } }, operations: true } },
      workOrders: true,
      assigned: { select: { id: true, name: true, email: true } },
    },
  });

  for (const component of bom.components) {
    const reserveQty = Math.ceil(component.quantityRequired * qty);
    try {
      await stockService.reserveStock(component.componentProductId, reserveQty);
    } catch (err) {
      if (!autoGenerated) throw err;
    }
  }

  return mo;
};

const startManufacturingOrder = async (moId) => {
  const mo = await prisma.manufacturingOrder.findUnique({
    where: { id: moId },
    include: { workOrders: true },
  });

  if (!mo) {
    throw Object.assign(new Error('Manufacturing order not found'), { statusCode: 404 });
  }
  if (mo.status !== 'DRAFT') {
    throw Object.assign(new Error('Only DRAFT manufacturing orders can be started'), { statusCode: 400 });
  }

  if (mo.workOrders.length > 0) {
    await prisma.workOrder.update({
      where: { id: mo.workOrders[0].id },
      data: { status: 'IN_PROGRESS' },
    });
  }

  return prisma.manufacturingOrder.update({
    where: { id: moId },
    data: { status: 'IN_PROGRESS' },
    include: {
      product: true,
      bom: { include: { components: { include: { componentProduct: true } }, operations: true } },
      workOrders: true,
      assigned: { select: { id: true, name: true, email: true } },
    },
  });
};

const completeWorkOrder = async (moId, woId) => {
  const wo = await prisma.workOrder.findFirst({
    where: { id: woId, manufacturingOrderId: moId },
  });

  if (!wo) {
    throw Object.assign(new Error('Work order not found'), { statusCode: 404 });
  }

  await prisma.workOrder.update({
    where: { id: woId },
    data: { status: 'DONE' },
  });

  const pendingWorkOrders = await prisma.workOrder.findMany({
    where: { manufacturingOrderId: moId, status: { not: 'DONE' } },
    orderBy: { id: 'asc' },
  });

  if (pendingWorkOrders.length > 0) {
    await prisma.workOrder.update({
      where: { id: pendingWorkOrders[0].id },
      data: { status: 'IN_PROGRESS' },
    });
  }

  return prisma.manufacturingOrder.findUnique({
    where: { id: moId },
    include: {
      product: true,
      bom: { include: { components: { include: { componentProduct: true } }, operations: true } },
      workOrders: true,
      assigned: { select: { id: true, name: true, email: true } },
    },
  });
};

const completeManufacturingOrder = async (moId) => {
  const mo = await prisma.manufacturingOrder.findUnique({
    where: { id: moId },
    include: {
      product: true,
      bom: { include: { components: true } },
    },
  });

  if (!mo) {
    throw Object.assign(new Error('Manufacturing order not found'), { statusCode: 404 });
  }
  if (!['DRAFT', 'IN_PROGRESS'].includes(mo.status)) {
    throw Object.assign(new Error('Manufacturing order cannot be completed in current status'), {
      statusCode: 400,
    });
  }

  for (const component of mo.bom.components) {
    const consumedQty = Math.ceil(component.quantityRequired * mo.quantity);
    await stockService.updateStock(
      component.componentProductId,
      -consumedQty,
      'MFG_CONSUMPTION',
      moId,
      'MANUFACTURING_ORDER'
    );
    await stockService.releaseReservedStock(component.componentProductId, consumedQty);
  }

  await stockService.updateStock(mo.productId, mo.quantity, 'MFG_PRODUCTION', moId, 'MANUFACTURING_ORDER');

  return prisma.manufacturingOrder.update({
    where: { id: moId },
    data: { status: 'COMPLETED' },
    include: {
      product: true,
      bom: { include: { components: { include: { componentProduct: true } }, operations: true } },
      workOrders: true,
      assigned: { select: { id: true, name: true, email: true } },
    },
  });
};

module.exports = {
  createManufacturingOrder,
  startManufacturingOrder,
  completeWorkOrder,
  completeManufacturingOrder,
};
