import prisma from '../config/db.js';
import * as stockService from './stockService.js';

const createPurchaseOrder = async (vendorId, items, userId, autoGenerated = false) => {
  const vendor = await prisma.vendor.findUnique({ where: { id: vendorId } });
  if (!vendor) {
    throw Object.assign(new Error('Vendor not found'), { statusCode: 404 });
  }

  return prisma.purchaseOrder.create({
    data: {
      vendorId,
      createdBy: userId,
      autoGenerated,
      status: 'DRAFT',
      items: {
        create: items.map((item) => ({
          productId: item.productId,
          quantity: item.quantity,
        })),
      },
    },
    include: {
      items: { include: { product: true } },
      vendor: true,
      creator: { select: { id: true, name: true, email: true } },
    },
  });
};

const confirmPurchaseOrder = async (orderId) => {
  const order = await prisma.purchaseOrder.findUnique({
    where: { id: orderId },
    include: { items: true },
  });

  if (!order) {
    throw Object.assign(new Error('Purchase order not found'), { statusCode: 404 });
  }
  if (order.status !== 'DRAFT') {
    throw Object.assign(new Error('Only DRAFT purchase orders can be confirmed'), { statusCode: 400 });
  }

  return prisma.purchaseOrder.update({
    where: { id: orderId },
    data: { status: 'CONFIRMED' },
    include: {
      items: { include: { product: true } },
      vendor: true,
      creator: { select: { id: true, name: true, email: true } },
    },
  });
};

const receivePurchaseOrder = async (orderId, receivedItems, userId) => {
  const order = await prisma.purchaseOrder.findUnique({
    where: { id: orderId },
    include: { items: true },
  });

  if (!order) {
    throw Object.assign(new Error('Purchase order not found'), { statusCode: 404 });
  }
  if (!['CONFIRMED', 'PARTIALLY_RECEIVED'].includes(order.status)) {
    throw Object.assign(new Error('Purchase order cannot be received in current status'), { statusCode: 400 });
  }

  for (const received of receivedItems) {
    const item = order.items.find((i) => i.id === received.itemId);
    if (!item) {
      throw Object.assign(new Error(`Item ${received.itemId} not found on order`), { statusCode: 400 });
    }

    const qtyToReceive = received.quantity;
    const remaining = item.quantity - item.receivedQty;
    if (qtyToReceive > remaining) {
      throw Object.assign(new Error(`Cannot receive more than remaining quantity for item ${item.id}`), {
        statusCode: 400,
      });
    }

    await stockService.updateStock(
      item.productId,
      qtyToReceive,
      'PURCHASE_RECEIPT',
      orderId,
      'PURCHASE_ORDER',
      userId
    );

    await prisma.purchaseOrderItem.update({
      where: { id: item.id },
      data: { receivedQty: item.receivedQty + qtyToReceive },
    });
  }

  const updatedItems = await prisma.purchaseOrderItem.findMany({
    where: { purchaseOrderId: orderId },
  });

  const allFullyReceived = updatedItems.every((i) => i.receivedQty >= i.quantity);
  const anyReceived = updatedItems.some((i) => i.receivedQty > 0);

  let newStatus = order.status;
  if (allFullyReceived) {
    newStatus = 'FULLY_RECEIVED';
  } else if (anyReceived) {
    newStatus = 'PARTIALLY_RECEIVED';
  }

  return prisma.purchaseOrder.update({
    where: { id: orderId },
    data: { status: newStatus },
    include: {
      items: { include: { product: true } },
      vendor: true,
      creator: { select: { id: true, name: true, email: true } },
    },
  });
};

const cancelPurchaseOrder = async (orderId) => {
  const order = await prisma.purchaseOrder.findUnique({ where: { id: orderId } });
  if (!order) {
    throw Object.assign(new Error('Purchase order not found'), { statusCode: 404 });
  }
  if (['FULLY_RECEIVED', 'CANCELLED'].includes(order.status)) {
    throw Object.assign(new Error('Purchase order cannot be cancelled'), { statusCode: 400 });
  }

  return prisma.purchaseOrder.update({
    where: { id: orderId },
    data: { status: 'CANCELLED' },
    include: {
      items: { include: { product: true } },
      vendor: true,
      creator: { select: { id: true, name: true, email: true } },
    },
  });
};

export {
  createPurchaseOrder,
  confirmPurchaseOrder,
  receivePurchaseOrder,
  cancelPurchaseOrder,
};
