export const ROLES = {
  ADMIN: 'ADMIN',
  SALES: 'SALES',
  PURCHASE: 'PURCHASE',
  MANUFACTURING: 'MANUFACTURING',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  OWNER: 'OWNER',
};

export const ROLE_GROUPS = {
  PRODUCT_FULL: [ROLES.ADMIN, ROLES.OWNER],
  PRODUCT_READ: [ROLES.SALES, ROLES.PURCHASE, ROLES.MANUFACTURING, ROLES.INVENTORY_MANAGER],
  SALES_FULL: [ROLES.ADMIN, ROLES.SALES],
  PURCHASE_FULL: [ROLES.ADMIN, ROLES.PURCHASE],
  MANUFACTURING_FULL: [ROLES.ADMIN, ROLES.MANUFACTURING],
  BOM_FULL: [ROLES.ADMIN, ROLES.MANUFACTURING],
  STOCK_FULL: [ROLES.ADMIN, ROLES.INVENTORY_MANAGER],
  AUDIT_FULL: [ROLES.ADMIN],
};
