import { useState } from 'react';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import TextField from '@mui/material/TextField';
import MenuItem from '@mui/material/MenuItem';
import Chip from '@mui/material/Chip';
import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import { Plus, Play, CheckCircle, CheckCircle2, Zap } from 'lucide-react';
import { useERP } from '../context/ERPContext';
import * as manufacturingOrderApi from '../api/manufacturingOrderApi';
import { mapManufacturingOrderFromApi } from '../api/mappers';
import { showError } from '../utils/helpers';

export default function Manufacturing() {
  const { data, updateData, addAuditLog, syncStockFromBackend, refreshStockLedger } = useERP();
  const [showForm, setShowForm] = useState(false);
  const [productId, setProductId] = useState('');
  const [quantity, setQuantity] = useState(1);

  const finishedGoods = data.products.filter((p) => p.type === 'Finished Good');

  const resetForm = () => {
    setProductId('');
    setQuantity(1);
    setShowForm(false);
  };

  const handleCreate = async () => {
    if (!productId || !quantity) {
      alert('Please select product and quantity');
      return;
    }
    try {
      const created = await manufacturingOrderApi.createManufacturingOrder({
        productId: Number(productId),
        quantity: Number(quantity),
      });
      const mapped = mapManufacturingOrderFromApi(created);
      updateData('manufacturingOrders', (prev) => [...prev, mapped]);
      await syncStockFromBackend();
      addAuditLog();
      resetForm();
    } catch (err) {
      showError(err, 'Failed to create manufacturing order');
    }
  };

  const handleStart = async (id) => {
    try {
      const updated = await manufacturingOrderApi.startMO(id);
      const mapped = mapManufacturingOrderFromApi(updated);
      updateData('manufacturingOrders', (prev) => prev.map((o) => (o.id === mapped.id ? mapped : o)));
      addAuditLog();
    } catch (err) {
      showError(err, 'Failed to start manufacturing order');
    }
  };

  const handleCompleteWorkOrder = async (moId, woId) => {
    try {
      const updated = await manufacturingOrderApi.completeWorkOrder(moId, woId);
      const mapped = mapManufacturingOrderFromApi(updated);
      updateData('manufacturingOrders', (prev) => prev.map((o) => (o.id === mapped.id ? mapped : o)));
      addAuditLog();
    } catch (err) {
      showError(err, 'Failed to complete work order');
    }
  };

  const handleCompleteMO = async (id) => {
    try {
      const updated = await manufacturingOrderApi.completeMO(id);
      const mapped = mapManufacturingOrderFromApi(updated);
      updateData('manufacturingOrders', (prev) => prev.map((o) => (o.id === mapped.id ? mapped : o)));
      await syncStockFromBackend();
      await refreshStockLedger(mapped.productId);
      addAuditLog();
    } catch (err) {
      showError(err, 'Failed to complete manufacturing order');
    }
  };

  const woStatusColor = (status) => {
    const map = { Pending: 'default', 'In Progress': 'info', Done: 'success' };
    return map[status] ?? 'default';
  };

  const moStatusColor = (status) => {
    const map = { Draft: 'default', 'In Progress': 'info', Completed: 'success', Cancelled: 'error' };
    return map[status] ?? 'default';
  };

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h2>Manufacturing Orders</h2>
          <p className="page-subtitle">Create and manage production orders</p>
        </div>
        <Button variant="contained" startIcon={<Plus size={16} />} onClick={() => setShowForm(true)}>
          New MO
        </Button>
      </div>

      <div className="flex flex-col gap-2">
        {data.manufacturingOrders.length === 0 && (
          <div className="card empty-row">No manufacturing orders yet</div>
        )}
        {data.manufacturingOrders.map((order) => (
          <Accordion key={order.id} className="card !shadow-sm">
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <div className="flex flex-wrap items-center gap-3 w-full pr-4">
                <span className="font-semibold flex items-center gap-1">
                  MO-{order.id}
                  {order.autoGenerated && (
                    <Chip label="Auto" color="warning" size="small" icon={<Zap size={14} />} />
                  )}
                </span>
                <span>{order.productName}</span>
                <span>Qty: {order.quantity}</span>
                <Chip label={order.status} color={moStatusColor(order.status)} size="small" />
              </div>
            </AccordionSummary>
            <AccordionDetails>
              <Table size="small" sx={{ mb: 2 }}>
                <TableHead>
                  <TableRow>
                    <TableCell>Operation</TableCell>
                    <TableCell>Work Center</TableCell>
                    <TableCell>Duration (min)</TableCell>
                    <TableCell>Status</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {order.workOrders.map((wo) => (
                    <TableRow key={wo.id}>
                      <TableCell>{wo.operationName}</TableCell>
                      <TableCell>{wo.workCenter || '—'}</TableCell>
                      <TableCell>{wo.durationMinutes}</TableCell>
                      <TableCell>
                        <Chip label={wo.status} color={woStatusColor(wo.status)} size="small" />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              <div className="table-actions flex flex-wrap gap-2">
                {order.status === 'Draft' && (
                  <Button
                    variant="contained"
                    size="small"
                    startIcon={<Play size={16} />}
                    onClick={() => handleStart(order.id)}
                  >
                    Start
                  </Button>
                )}
                {order.status === 'In Progress' && (
                  <>
                    {order.workOrders
                      .filter((wo) => wo.status !== 'Done')
                      .map((wo) => (
                        <Button
                          key={wo.id}
                          variant="outlined"
                          size="small"
                          startIcon={<CheckCircle size={16} />}
                          onClick={() => handleCompleteWorkOrder(order.id, wo.id)}
                        >
                          Complete {wo.operationName}
                        </Button>
                      ))}
                    {order.workOrders.every((wo) => wo.status === 'Done') && (
                      <Button
                        variant="contained"
                        color="success"
                        size="small"
                        startIcon={<CheckCircle2 size={16} />}
                        onClick={() => handleCompleteMO(order.id)}
                      >
                        Complete MO
                      </Button>
                    )}
                  </>
                )}
                {order.status === 'Completed' && (
                  <Chip label="Completed" color="success" icon={<CheckCircle2 size={14} />} size="small" />
                )}
              </div>
            </AccordionDetails>
          </Accordion>
        ))}
      </div>

      <Dialog open={showForm} onClose={resetForm} maxWidth="sm" fullWidth>
        <DialogTitle>Create Manufacturing Order</DialogTitle>
        <DialogContent>
          <div className="flex flex-col gap-4 pt-2">
            <TextField
              select
              fullWidth
              size="small"
              label="Finished Product"
              value={productId}
              onChange={(e) => setProductId(e.target.value)}
            >
              <MenuItem value="">Select product</MenuItem>
              {finishedGoods.map((p) => (
                <MenuItem key={p.id} value={p.id}>
                  {p.name} ({p.sku})
                </MenuItem>
              ))}
            </TextField>
            <TextField
              type="number"
              fullWidth
              size="small"
              label="Quantity"
              value={quantity}
              onChange={(e) => setQuantity(e.target.value)}
              inputProps={{ min: 1 }}
            />
          </div>
        </DialogContent>
        <DialogActions>
          <Button onClick={resetForm}>Cancel</Button>
          <Button variant="contained" onClick={handleCreate}>Create MO</Button>
        </DialogActions>
      </Dialog>
    </div>
  );
}
