import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import TextField from '@mui/material/TextField';
import MenuItem from '@mui/material/MenuItem';
import Chip from '@mui/material/Chip';
import Box from '@mui/material/Box';
import { Plus, Zap } from 'lucide-react';
import { useERP } from '../context/ERPContext';
import * as manufacturingOrderApi from '../api/manufacturingOrderApi';
import { mapManufacturingOrderFromApi } from '../api/mappers';
import { showError } from '../utils/helpers';

export default function Manufacturing() {
  const navigate = useNavigate();
  const { data, updateData, addAuditLog, syncStockFromBackend } = useERP();
  const [showForm, setShowForm] = useState(false);
  const [productId, setProductId] = useState('');
  const [quantity, setQuantity] = useState(1);

  const finishedGoods = data.products.filter((p) => p.type === 'Finished Good');

  const resetForm = () => {
    setProductId('');
    setQuantity(1);
    setShowForm(false);
  };

  const handleCreate = async () => {
    if (!productId || !quantity) {
      alert('Please select product and quantity');
      return;
    }
    try {
      const created = await manufacturingOrderApi.createManufacturingOrder({
        productId: Number(productId),
        quantity: Number(quantity),
      });
      const mapped = mapManufacturingOrderFromApi(created);
      updateData('manufacturingOrders', (prev) => [...prev, mapped]);
      await syncStockFromBackend();
      addAuditLog();
      resetForm();
      navigate(`/manufacturing-orders/${mapped.id}`);
    } catch (err) {
      showError(err, 'Failed to create manufacturing order');
    }
  };

  const moStatusColor = (status) => {
    const map = { Draft: 'default', 'In Progress': 'info', Completed: 'success', Cancelled: 'error' };
    return map[status] ?? 'default';
  };

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h2>Manufacturing Orders</h2>
          <p className="page-subtitle">Create and manage production orders</p>
        </div>
        <Button variant="contained" startIcon={<Plus size={16} />} onClick={() => setShowForm(true)}>
          New MO
        </Button>
      </div>

      <div className="flex flex-col gap-2">
        {data.manufacturingOrders.length === 0 && (
          <div className="card empty-row">No manufacturing orders yet</div>
        )}
        {data.manufacturingOrders.map((mo) => (
          <Box
            key={mo.id}
            className="card"
            onClick={() => navigate(`/manufacturing-orders/${mo.id}`)}
            sx={{
              cursor: 'pointer',
              transition: 'box-shadow 0.2s',
              '&:hover': { boxShadow: 3 },
            }}
          >
            <div className="flex flex-wrap items-center gap-3 w-full">
              <span className="font-semibold flex items-center gap-1">
                MO-{mo.id}
                {mo.autoGenerated && (
                  <Chip label="Auto" color="warning" size="small" icon={<Zap size={14} />} />
                )}
              </span>
              <span>{mo.productName}</span>
              <span>Qty: {mo.quantity}</span>
              <Chip label={mo.status} color={moStatusColor(mo.status)} size="small" />
              <span className="text-sm text-slate-500 ml-auto">
                {mo.workOrders?.length ?? 0} work orders
              </span>
            </div>
          </Box>
        ))}
      </div>

      <Dialog open={showForm} onClose={resetForm} maxWidth="sm" fullWidth>
        <DialogTitle>Create Manufacturing Order</DialogTitle>
        <DialogContent>
          <div className="flex flex-col gap-4 pt-2">
            <TextField
              select
              fullWidth
              size="small"
              label="Finished Product"
              value={productId}
              onChange={(e) => setProductId(e.target.value)}
            >
              <MenuItem value="">Select product</MenuItem>
              {finishedGoods.map((p) => (
                <MenuItem key={p.id} value={p.id}>
                  {p.name} ({p.sku})
                </MenuItem>
              ))}
            </TextField>
            <TextField
              type="number"
              fullWidth
              size="small"
              label="Quantity"
              value={quantity}
              onChange={(e) => setQuantity(e.target.value)}
              inputProps={{ min: 1 }}
            />
          </div>
        </DialogContent>
        <DialogActions>
          <Button onClick={resetForm}>Cancel</Button>
          <Button variant="contained" onClick={handleCreate}>
            Create MO
          </Button>
        </DialogActions>
      </Dialog>
    </div>
  );
}
