import { useState } from 'react';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import TextField from '@mui/material/TextField';
import MenuItem from '@mui/material/MenuItem';
import Chip from '@mui/material/Chip';
import { DataGrid } from '@mui/x-data-grid';
import { Plus, Trash2, Zap } from 'lucide-react';
import { useERP } from '../context/ERPContext';
import * as purchaseOrderApi from '../api/purchaseOrderApi';
import * as vendorApi from '../api/vendorApi';
import { mapPurchaseOrderFromApi, toReceivePayload } from '../api/mappers';
import EntityAutocomplete from '../components/common/EntityAutocomplete';
import { formatCurrency, formatDate, showError } from '../utils/helpers';

const emptyItem = { productId: '', quantity: 1 };

export default function Purchase() {
  const { data, updateData, addAuditLog, syncStockFromBackend, refreshVendors } = useERP();
  const [showForm, setShowForm] = useState(false);
  const [vendorId, setVendorId] = useState('');
  const [items, setItems] = useState([{ ...emptyItem }]);

  const rawMaterials = data.products.filter((p) => p.type === 'Raw Material');

  const calcTotal = (lineItems) =>
    lineItems.reduce((sum, item) => {
      const product = data.products.find((p) => p.id === Number(item.productId));
      return sum + (Number(item.quantity) || 0) * (product?.costPrice ?? 0);
    }, 0);

  const handleAddLine = () => setItems([...items, { ...emptyItem }]);

  const handleRemoveLine = (idx) => {
    if (items.length <= 1) return;
    setItems(items.filter((_, i) => i !== idx));
  };

  const handleItemChange = (idx, field, value) => {
    const next = [...items];
    next[idx] = { ...next[idx], [field]: value };
    setItems(next);
  };

  const resetForm = () => {
    setVendorId('');
    setItems([{ ...emptyItem }]);
    setShowForm(false);
  };

  const handleCreateVendor = async (payload) => {
    const created = await vendorApi.createVendor(payload);
    await refreshVendors();
    return created;
  };

  const handleCreate = async () => {
    if (!vendorId || items.some((i) => !i.productId || !i.quantity)) {
      alert('Please select vendor and fill all line items');
      return;
    }
    try {
      const payload = {
        vendorId: Number(vendorId),
        items: items.map((i) => ({
          productId: Number(i.productId),
          quantity: Number(i.quantity),
        })),
      };
      const created = await purchaseOrderApi.createPurchaseOrder(payload);
      const mapped = mapPurchaseOrderFromApi(created);
      if (!mapped.total) mapped.total = calcTotal(items);
      updateData('purchaseOrders', (prev) => [...prev, mapped]);
      addAuditLog();
      resetForm();
    } catch (err) {
      showError(err, 'Failed to create purchase order');
    }
  };

  const advanceStatus = async (order) => {
    try {
      let updated;
      if (order.status === 'Draft') {
        updated = await purchaseOrderApi.confirmPurchaseOrder(order.id);
      } else if (order.status === 'Confirmed' || order.status === 'Partially Received') {
        const receiveItems = toReceivePayload(order.items);
        updated = await purchaseOrderApi.receivePurchaseOrder(order.id, receiveItems);
        await syncStockFromBackend();
      } else {
        return;
      }

      const mapped = mapPurchaseOrderFromApi(updated);
      updateData('purchaseOrders', (prev) => prev.map((o) => (o.id === mapped.id ? mapped : o)));
      addAuditLog();
    } catch (err) {
      showError(err, 'Failed to update purchase order');
    }
  };

  const handleCancel = async (order) => {
    try {
      const updated = await purchaseOrderApi.cancelPurchaseOrder(order.id);
      const mapped = mapPurchaseOrderFromApi(updated);
      updateData('purchaseOrders', (prev) => prev.map((o) => (o.id === mapped.id ? mapped : o)));
      addAuditLog();
    } catch (err) {
      showError(err, 'Failed to cancel purchase order');
    }
  };

  const getActionLabel = (status) => {
    if (status === 'Draft') return 'Confirm';
    if (status === 'Confirmed' || status === 'Partially Received') return 'Receive';
    return null;
  };

  const statusColor = (status) => {
    const map = {
      Draft: 'default',
      Confirmed: 'info',
      'Partially Received': 'warning',
      'Fully Received': 'success',
      Cancelled: 'error',
    };
    return map[status] ?? 'default';
  };

  const columns = [
    {
      field: 'id',
      headerName: 'PO #',
      width: 130,
      renderCell: ({ row }) => (
        <span className="flex items-center gap-1">
          PO-{row.id}
          {row.autoGenerated && (
            <Chip label="Auto" color="warning" size="small" icon={<Zap size={14} />} />
          )}
        </span>
      ),
    },
    { field: 'vendorName', headerName: 'Vendor', flex: 1 },
    {
      field: 'orderDate',
      headerName: 'Date',
      width: 120,
      valueFormatter: (v) => formatDate(v),
    },
    {
      field: 'status',
      headerName: 'Status',
      width: 160,
      renderCell: ({ value }) => <Chip label={value} color={statusColor(value)} size="small" />,
    },
    {
      field: 'total',
      headerName: 'Total',
      width: 120,
      valueFormatter: (v) => formatCurrency(v),
    },
    {
      field: 'actions',
      headerName: 'Actions',
      width: 200,
      sortable: false,
      renderCell: ({ row }) => (
        <div className="flex gap-1 flex-wrap">
          {getActionLabel(row.status) && (
            <Button size="small" variant="contained" onClick={() => advanceStatus(row)}>
              {getActionLabel(row.status)}
            </Button>
          )}
          {!['Fully Received', 'Cancelled'].includes(row.status) && (
            <Button size="small" color="error" variant="outlined" onClick={() => handleCancel(row)}>
              Cancel
            </Button>
          )}
        </div>
      ),
    },
  ];

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h2>Purchase Orders</h2>
          <p className="page-subtitle">Create, confirm, and receive purchase orders</p>
        </div>
        <Button variant="contained" startIcon={<Plus size={16} />} onClick={() => setShowForm(true)}>
          New Purchase Order
        </Button>
      </div>

      <div className="card p-0 overflow-hidden">
        <DataGrid
          rows={data.purchaseOrders}
          columns={columns}
          autoHeight
          pageSizeOptions={[10, 25]}
          initialState={{ pagination: { paginationModel: { pageSize: 10 } } }}
          disableRowSelectionOnClick
        />
      </div>

      <Dialog open={showForm} onClose={resetForm} maxWidth="md" fullWidth>
        <DialogTitle>Create Purchase Order</DialogTitle>
        <DialogContent>
          <div className="flex flex-col gap-4 pt-2">
            <EntityAutocomplete
              label="Vendor"
              options={data.vendors}
              value={vendorId}
              onChange={setVendorId}
              onCreate={handleCreateVendor}
            />
            <div>
              <h4 className="text-sm font-semibold mb-2">Line Items</h4>
              {items.map((item, idx) => (
                <div key={idx} className="flex gap-2 mb-2 items-center">
                  <TextField
                    select
                    size="small"
                    label="Product"
                    value={item.productId}
                    onChange={(e) => handleItemChange(idx, 'productId', e.target.value)}
                    sx={{ flex: 2 }}
                  >
                    <MenuItem value="">Select product</MenuItem>
                    {rawMaterials.map((p) => (
                      <MenuItem key={p.id} value={p.id}>
                        {p.name} ({p.sku})
                      </MenuItem>
                    ))}
                  </TextField>
                  <TextField
                    type="number"
                    size="small"
                    label="Qty"
                    value={item.quantity}
                    onChange={(e) => handleItemChange(idx, 'quantity', e.target.value)}
                    inputProps={{ min: 1 }}
                    sx={{ width: 100 }}
                  />
                  <Button size="small" color="error" onClick={() => handleRemoveLine(idx)}>
                    <Trash2 size={16} />
                  </Button>
                </div>
              ))}
              <Button size="small" variant="outlined" startIcon={<Plus size={14} />} onClick={handleAddLine}>
                Add Line
              </Button>
            </div>
            <p className="font-semibold">Total: {formatCurrency(calcTotal(items))}</p>
          </div>
        </DialogContent>
        <DialogActions>
          <Button onClick={resetForm}>Cancel</Button>
          <Button variant="contained" onClick={handleCreate}>Create Order</Button>
        </DialogActions>
      </Dialog>
    </div>
  );
}
